hit = false;
is_projectile = false;
is_enemy = true;
max_hitpoint = 150;
hitpoint = max_hitpoint;
defense = 10;
damage = 50;
range = 30;
spd = 5;
in_range = false;
swing_speed = 60;
cooldown = swing_speed;
obj_wave_manager.enemies_remaining++;
parent_instance = noone;
